### PR TITLE
fix #2485 for some types requiring a scalar

### LINKED ISSUE #2485: Defined type from a basic type should not need a mandatory scalar + MarshalFunc and UnmarshalFunc
### What happened?

In an existing Golang project where we are trying to add `gqlgen`, we have defined some types from basic types (string, int, boolean, float) that are being used in other structs. Currently, we need to write a `scalar` in the GraphQL schema and also do a `MarshalFunc` and `UnmarshalFunc` in order to avoid an error message saying `<type> is incompatible with <named_type>`.

image

### What did you expect?

No error message appear and no need to create a `scalar` with related `MarshalFunc` and `UnmarshalFunc` when `go generate`.

### Minimal graphql.schema and models to reproduce

In a remote package, create some named basic types:
```go
package namedtypes

type (
	NamedString  string
	NamedInt     int
	NamedInt32   int32
	NamedInt64   int64
	NamedBool    bool
	NamedFloat64 float64
)
```
In another package, create a struct using these named basic types (might need to add this package to autobind):
```go
package usenamedtypes

import "github.com/99designs/gqlgen/integration/namedtypes"

type DummyUser struct {
	NewString  namedtypes.NamedString
	NewInt     namedtypes.NamedInt
	NewInt32   namedtypes.NamedInt32
	NewInt64   namedtypes.NamedInt64
	NewBool    namedtypes.NamedBool
	NewFloat64 namedtypes.NamedFloat64
}
```
In the GraphQL schema, create a type for the struct:
```graphql
type DummyUser {
    NewString: String!
    NewInt: Int!
    NewInt32: Int!
    NewInt64: Int!
    NewBool: Boolean!
    NewFloat64: Float!
}
```

Please note that a PR is coming to fix this.

### versions
 - `go run github.com/99designs/gqlgen version`? v0.17.22-dev
 - `go version`? go1.19.3 darwin/arm64

### PR DESCRIPTION
**Pull request by mstephano**
Following PR # [2486](https://github.com/99designs/gqlgen/pull/2486), some types require a scalar to work properly. This PR fixes some of them except `float32` and `uint64`. The reasons are as follow:

- float32: the precision changed when marshalling/unmarshalling from float64 back to float32. As an example, value of 5.76 comes out as 5.760000228881836. Anyone knows how to fix this? You can see this [branch](https://github.com/mstephano/gqlgen/tree/fix/float32) for an example, or precisely this [commit](https://github.com/mstephano/gqlgen/commit/9ee30a5d9897a82b3a9db7fb752504530e05613d).
- uint64: it is bigger than int64

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [ ] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

File: codegen/config/binder.go [hunk 1]
```diff
@@ -257,6 +257,30 @@ func (t *TypeReference) IsUnderlyingBasic() bool {
 	return isUnderlyingBasic
 }
 
+func (t *TypeReference) IsUnusualBasic() bool {
```
Comment (mstephano) [inline codegen/config/binder.go:260]: I named these as `Unusual` but a suggestion for a better name is welcomed.

**Comment by mojtabacazi** [comment]
This commit actually broke our app, it generates invalid code when trying to unmarshal typed scalars. It evens breaks `time.Duration` types to name a few. Here is an example:

```
func (ec *executionContext) unmarshalNInt642timeᚐDuration(ctx context.Context, v interface{}) (time.Duration, error) {
	res, err := graphql.UnmarshalInt64(v)
	return res, graphql.ErrorOnPath(ctx, err)
}
```
which causes this error:

```
cannot use res (variable of type int64) as type time.Duration in return statement
```

Here is another example with a pointer type

```
func (ec *executionContext) unmarshalOBoolean2DummyFilter(ctx context.Context, v interface{}) (*dummy.DummyFilter, error) {
	if v == nil {
		return nil, nil
	}
	res, err := graphql.UnmarshalBoolean(v)
	return &res, graphql.ErrorOnPath(ctx, err)
}
```

**Comment by StevenACoffman** [comment]
@mojtabacazi Did #2528 fix your issue?

**Comment by StevenACoffman** [comment]
also related: #2486

**Comment by mojtabacazi** [comment]
> @mojtabacazi Did #2528 fix your issue?

Nope

**Comment by StevenACoffman** [comment]
@mojtabacazi I reverted this, so please see if v0.17.27 resolves your issue!
