### PR TITLE
Use pointers when embedding structs in generated structs

### LINKED ISSUE #585: not possible to use schema with cyclic graph?
### Expected Behaviour

Schema should be able to have cycles.

### Actual Behavior

Schema with cycles generates structs with dependencies on other structs that lead to an error.

### Minimal graphql.schema and models to reproduce

I've taken the following example from https://swapi.graph.cool/ to illustrate a cycle.

To be able to perform this query:
```
query {
    allPersons {
      name
      birthYear
      species {
        people {
          name
          birthYear
        }
      }
    }
}
```

You would need to have this part of the schema:
```graphql
interface Node {
  id: ID!
}

type Person implements Node {
  name: String!
  birthYear: String
  species: [Species!]
}

type Species implements Node {
  name: String!
  people: [Person!]
}
```

But that leads to a problem with gengql generating cycling dependency between structs.

### PR DESCRIPTION
**Pull request by vektah**
modelgen currently tries to turn
```graphql
type LoopA {
    b: LoopB!
}

 type LoopB {
    a: LoopA!
}
```

into 
```go
type LoopA struct {
	B LoopB
}

 type LoopB struct {
	A LoopA
}
```
Which is invalid. 

This PR adds pointers whenever embedding a struct in a struct to avoid this.

Fixes #585 #586 #693 

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [x] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

File: plugin/modelgen/out/generated.go [hunk 1]
```diff
@@ -37,7 +37,7 @@ type MissingType struct {
 	Name     *string          `json:"name"`
 	Enum     *MissingEnum     `json:"enum"`
 	Int      MissingInterface `json:"int"`
-	Existing *ExistingType    `json:"existing"`
+	Existing **ExistingType   `json:"existing"`
```
Comment (lwc) [inline plugin/modelgen/out/generated.go]: is this double pointer intentional?

Comment (vektah) [reply plugin/modelgen/out/generated.go]: Good catch!
