### PR TITLE
Fix #1834: Implement federation correctly

### LINKED ISSUE #1090: Apollo Federation: 422: Unprocessable Entity when no entity defined
### What happened?

There is a service which only contains a mutation which has only input types defined:

```
extend type Mutation {
  addSurveyResult(result: SurveyResult!): ID
}

input SurveyResultTuple {
     key: String
     value: String
}

input SurveyResult {
  userId: ID!

  type: String!

  elements: [SurveyResultTuple!]!
}
```

when I try to federate the service by a gateway the following errors occure:

Service:
>unknown field "_service"
>
> goroutine 9 [running]:
> runtime/debug.Stack(0x1, 0x0, 0x0)
>         /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
> runtime/debug.PrintStack()
>         /usr/local/go/src/runtime/debug/stack.go:16 +0x22
> github.com/99designs/gqlgen/graphql.DefaultRecover(0xc0c740, 0xc0002c8690, 0x9fe620, 0xc0001b8de0, 0x44900f, 0x18)
>         /home/simon/go/pkg/mod/github.com/99designs/gqlgen@v0.11.1/graphql/recovery.go:16 +0xa7
> github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP.func1(0xc0000d5e40, 0xc00013fbd0, 0xc0ae40, 0xc0002922a0)
>         /home/simon/go/pkg/mod/github.com/99designs/gqlgen@v0.11.1/graphql/handler/server.go:124 +0xa7
> panic(0x9fe620, 0xc0001b8de0)
>         /usr/local/go/src/runtime/panic.go:679 +0x1b2
> recommender-survey-archive/cmd/graph/generated.(*executionContext)._Query(0xc0001b8da0, 0xc0c740, 0xc0002c8ff0, 0xc0001b8b40, 0x1, 0x1, 0x40dcc6, 0xc0002c8fc0)
>         /home/simon/go/src/recommender-survey-archive/cmd/graph/generated/generated.go:1527 +0x6b4
> recommender-survey-archive/cmd/graph/generated.(*executableSchema).Exec.func1(0xc0c740, 0xc0002c8fc0, 0x10)
>         /home/simon/go/src/recommender-survey-archive/cmd/graph/generated/generated.go:99 +0x7b
> github.com/99designs/gqlgen/graphql/handler.executor.DispatchOperation.func1.1.1(0xc0c740, 0xc0002c8fc0, 0xc0001b8db0)
>         /home/simon/go/pkg/mod/github.com/99designs/gqlgen@v0.11.1/graphql/handler/executor.go:100 +0x43
> github.com/99designs/gqlgen/graphql/handler.newExecutor.func2(0xc0c740, 0xc0002c8fc0, 0xc0001b8db0, 0xbeec60)
>         /home/simon/go/pkg/mod/github.com/99designs/gqlgen@v0.11.1/graphql/handler/executor.go:33 +0x3a
> github.com/99designs/gqlgen/graphql/handler.executor.DispatchOperation.func1.1(0xc0c740, 0xc0002c8f60, 0xc0002c8690)
>         /home/simon/go/pkg/mod/github.com/99designs/gqlgen@v0.11.1/graphql/handler/executor.go:99 +0x130
> github.com/99designs/gqlgen/graphql/handler/transport.POST.Do(0xc0ae40, 0xc0002922a0, 0xc00028e300, 0xc0b300, 0xc0000c0ff0)
>         /home/simon/go/pkg/mod/github.com/99designs/gqlgen@v0.11.1/graphql/handler/transport/http_post.go:52 +0x353
> github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc0000d5e40, 0xc0ae40, 0xc0002922a0, 0xc00028e300)
>         /home/simon/go/pkg/mod/github.com/99designs/gqlgen@v0.11.1/graphql/handler/server.go:140 +0x23c
> net/http.(*ServeMux).ServeHTTP(0x106d9c0, 0xc0ae40, 0xc0002922a0, 0xc00028e200)
>         /usr/local/go/src/net/http/server.go:2387 +0x1bd
> net/http.serverHandler.ServeHTTP(0xc0002921c0, 0xc0ae40, 0xc0002922a0, 0xc00028e200)
>         /usr/local/go/src/net/http/server.go:2802 +0xa4
> net/http.(*conn).serve(0xc000270b40, 0xc0c680, 0xc000290b00)
>         /usr/local/go/src/net/http/server.go:1890 +0x875
> created by net/http.(*Server).Serve
>         /usr/local/go/src/net/http/server.go:2928 +0x384

Gateway:

> Encountered error when loading recommender-survey-archive at http://localhost:4004/query: 422: Unprocessable Entity

When the following graphql type is added everything works smoothly

```
type Workaround @key(fields: "id") {
  id: Int
}
```

**Note**: @key is required for this workaround

### What did you expect?

I don't understand the details but I would expect gqlgen to add the following Query without the **Workaround** type, so that the service can be federated:

```
extend type Query {
   _entities(representations: [_Any!]!): [_Entity]!
   _service: _Service!
}
```

### Minimal graphql.schema and models to reproduce

See above.

### versions
 - `gqlgen version`? 

v0.11.1

 - `go version`?

go version go1.13.6 linux/amd64

EDIT: Btw. I want to thank you for providing a go lib that allows to federate with apollo. You have created a really smooth technology that helps me a lot, great job and thank you!

### LINKED ISSUE #1724: expose federation implementation when federation is enabled
### Background
I started a new subgraph which doesn't yet need federation but would like to be a part of subgraph.

another scenario is that, with federation 2, I have a type which doesn't need a identifier. (so no `@key` directive)

### What happened?
When I try to see if this server is federation compliant (rover sends a query which fails) the reason it fails is when gqlgen doesn't see any types which are using any federated directives, it simply hides all the fields that were needed for federation. When I query for `_service {sdl}` it says the type service is not found and returns a 422.

### What did you expect?
Even if I'm not using any of the federation directives, it should still expose the schema in a way that it's compatible with federation.

### Minimal graphql.schema and models to reproduce
```graphql
type ApiInfo {
    version: String!
}
type Query {
  apiInfo: ApiInfo!
}
```

If you run this and try to see if this is federation compliant even with the flag enabled, it'd seem that it's not.

### versions
 - `gqlgen version`? 0.13.0
 - `go version`? 1.16.4
 - dep or go modules? go mod

But I don't think versioning is the issue here.

Or is there something I'm missing? Is there any trick that I can use for now?

### LINKED ISSUE #1834: Current implementation of federation does not conform to the Apollo Federation subgraph specification
### What happened?
There are several issues in federation implementation according to the [Apollo Federation subgraph specification](https://www.apollographql.com/docs/federation/federation-spec):
1. When customizing root query type, _service is not generated in customized query struct. Then Apollo gateway cannot get service definition in subgraph.
2. If @key directive is not used in graphql schema, both _service and _entities are not generated.

### What did you expect?
1. _service is generated in customized query struct.
2. _service is generated in any case, while _entities is generated only when @key directive exists.

### Minimal graphql.schema and models to reproduce
```
schema {
    query: CustomQuery
}

type Hello {
  name: String!
}

type CustomQuery {
  hello: Hello!
}
```

### versions
 - `gqlgen version` 0.15.1
 - `go version` 1.17
 - dep or go modules? go modules

### PR DESCRIPTION
**Pull request by newerbie**
Fix #1834
Fix #1724
Fix #1090
See also #1192

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))

---

There are several issues in federation implementation according to the [Apollo Federation subgraph specification](https://www.apollographql.com/docs/federation/federation-spec):
1. When customizing root query type, _service is not generated in customized query struct. Then Apollo gateway cannot get service definition in subgraph.
2. If @key directive is not used in graphql schema, both _service and _entities are not generated.

### What did you expect?
1. _service is generated in customized query struct.
2. _service is generated in any case, while _entities is generated only when @key directive exists.

### Minimal graphql.schema and models to reproduce
```
schema {
    query: CustomQuery
}

type Hello {
  name: String!
}

type CustomQuery {
  hello: Hello!
}
```

### versions
 - `gqlgen version` 0.15.1
 - `go version` 1.17
 - dep or go modules? go modules

### CODE REVIEW

**Comment by StevenACoffman** [comment]
Hi! It looks like you need to run `cd example; go generate ./...` and commit the changes

File: plugin/federation/federation.go [hunk 1]
```diff
@@ -132,22 +132,33 @@ type Entity {
...
-		Input: `
-# a union of all types that use the @key directive
-union _Entity = ` + entities + `
-` + resolvers + `
+	_serviceTypeDef := `
 type _Service {
   sdl: String
-}
+}`
+	additionalQueryFields := ``
```
Comment (a8m) [inline plugin/federation/federation.go:139]:
```suggestion
	var additionalQueryFields string
```

**Comment by newerbie** [comment]
> Hi! It looks like you need to run `cd example; go generate ./...` and commit the changes

Hi, I just reorganized the code related to line break generation, and after ran `cd example; go generate ./...`, nothing changed in all generated.go files, thanks for the tip.

File: plugin/federation/federation.go (hunk 1 above)
Comment (newerbie) [reply plugin/federation/federation.go]: Hi, I have adjusted the code, please review it again at your convenience, thank you.

**Comment by newerbie** [comment]
> > Hi! It looks like you need to run `cd example; go generate ./...` and commit the changes
> 
> Hi, I just reorganized the code related to line break generation, and after ran `cd example; go generate ./...`, nothing changed in all generated.go files, thanks for the tip.

I am so sorry it failed at lint stage again. I checked `go:generate` throughout the project, and ran `go generate ./...` again, there were two added line breaks in plugin/federation/testdata/entityresolver/generated/exec.go. I think it's ok now.

**Comment by StevenACoffman** [comment]
Thanks!
